m4_divert(-1)
m4_define(`m4_substlist',`')
m4_define(`m4_quote',``$@'')
m4_define(`m4_addsubst',`m4_define(`m4_substlist',m4_quote(m4_substlist,`$1',`$2'))')
m4_define(`m4_dosubsts',`m4_ifelse(`$2',`',`$1',`m4_dosubsts(m4_quote(m4_patsubst(`$1',`$2',`$3')),m4_shift(m4_shift(m4_shift($@))))')')
m4_define(`m4_forth',`m4_dosubsts(`$1',m4_shift(m4_substlist))')
	^ lazy hack: shifting the substlist removes empty first item
m4_define(`m4_chop',`m4_substr(`$1',0,m4_eval(m4_len(`$1')-1))')
m4_addsubst(`: \(.*\) ( +\([a-z_]+\) )',``m4_forthword(`\1',\2,'')
m4_addsubst(`;',`EXIT)')
m4_addsubst(`( +[^)]*)',`')
m4_addsubst(` \([0-9]+\) ',`PUSH(\1),')
m4_addsubst(`BEGIN \(.*\) WHILE \(.*\) REPEAT',`m4_BEGIN_WHILE_REPEAT(m4_chop(`\1'),m4_chop(`\2'))')
m4_addsubst(`BEGIN \(.*\) UNTIL',`m4_BEGIN_UNTIL(m4_chop(`\1'))')
m4_addsubst(`BEGIN \(.*\) AGAIN',`m4_BEGIN_AGAIN(m4_chop(`\1'))')
m4_addsubst(`IF \(.*\) ELSE \(.*\) THEN',`m4_IF_ELSE(m4_chop(`\1'),m4_chop(`\2'))')
m4_addsubst(`IF \(.*\) THEN',`m4_IF(`\1')')
m4_divert(0)m4_dnl
m4_addsubst(`LSHIFT',`lsh_code,')m4_dnl
m4_forth(m4_include(2mul.fth))
